
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: postgres-user-secure
    environment:
      POSTGRES_DB: SECURE_DB  #${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: enki  #${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: enki  #${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  pgadmin:
    container_name: pgadmin4-user-secure
    image: dpage/pgadmin4:latest
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: enki@enki.com
      PGADMIN_DEFAULT_PASSWORD: enki
    ports:
      - "5050:80"


volumes:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
